# permissions for end users to edit bitwardensecrets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: bitwardensecret-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: bitwarden-provider
    app.kubernetes.io/part-of: bitwarden-provider
    app.kubernetes.io/managed-by: kustomize
  name: bitwardensecret-editor-role
rules:
- apiGroups:
  - bitwarden.provider.matteogastaldello.provider
  resources:
  - bitwardensecrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - bitwarden.provider.matteogastaldello.provider
  resources:
  - bitwardensecrets/status
  verbs:
  - get
