---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - bitwarden.provider.matteogastaldello.provider
  resources:
  - bitwardensecrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - bitwarden.provider.matteogastaldello.provider
  resources:
  - bitwardensecrets/finalizers
  verbs:
  - update
- apiGroups:
  - bitwarden.provider.matteogastaldello.provider
  resources:
  - bitwardensecrets/status
  verbs:
  - get
  - patch
  - update
