apiVersion: bitwarden.provider.matteogastaldello.provider/v1
kind: ConnectorConfig
metadata:
  name: connectorconfig-sample
spec:
  apiUrl: http://host.docker.internal:8087 
  credentials:
    secretRef:
      namespace: default
      name: bitwarden-password
      key: password
  