apiVersion: bitwarden.provider.matteogastaldello.provider/v1
kind: ConnectorConfig
metadata:
  name: connectorconfig-sample
spec:
  apiUrl: https://dev.azure.com
  credentials:
    secretRef:
      namespace: default
      name: bitwarden-password
      key: password
  